import { FormEvent, useMemo, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { ArrowLeft, CalendarDays, Clock3, Users, CheckCircle2 } from 'lucide-react';
import { useAuth } from '@/context/AuthContext';
import { useToast } from '@/context/ToastContext';
import { createTableBooking } from '@/lib/api';
import { Input, Textarea } from '@/components/ui/Input';
import Button from '@/components/ui/Button';

export default function BookTablePage(){
  const { profile, session } = useAuth();
  const { showToast } = useToast();
  const navigate = useNavigate();
  const today = useMemo(() => new Date().toISOString().slice(0,10), []);
  const [form,setForm]=useState({customerName:profile?.name||'',customerPhone:profile?.phone||'',customerEmail:session?.user?.email||'',date:today,time:'19:00',guests:'2',notes:''});
  const [done,setDone]=useState<{bookingNumber:string}|null>(null);
  const [loading,setLoading]=useState(false);
  const update=(key:string,value:string)=>setForm(p=>({...p,[key]:value}));
  const submit=async(e:FormEvent)=>{e.preventDefault();if(!form.customerName.trim()||!form.customerPhone.trim()||!form.date||!form.time){showToast('Please fill all required details','error');return;}setLoading(true);try{const booking=await createTableBooking({...form,guests:Number(form.guests)});setDone({bookingNumber:booking.bookingNumber});showToast('Table booking request sent!','success');}catch(err:any){showToast(err.message||'Unable to book table','error');}finally{setLoading(false);}};
  if(done)return <div className="container-narrow py-16 lg:py-24"><div className="mx-auto max-w-xl rounded-3xl border border-emerald-500/20 bg-ink-900 p-8 text-center"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-emerald-500/10"><CheckCircle2 className="h-8 w-8 text-emerald-400"/></div><h1 className="mt-5 font-display text-3xl font-bold text-cream-50">Table Request Received</h1><p className="mt-3 text-sm text-ink-300">Your booking <span className="font-semibold text-cream-100">{done.bookingNumber}</span> is pending confirmation from AL NIHAR.</p><div className="mt-7 flex justify-center gap-3"><Link to="/" className="rounded-xl border border-ink-600 px-5 py-3 text-sm font-semibold text-cream-100">Back Home</Link><Link to="/menu" className="rounded-xl bg-ember-500 px-5 py-3 text-sm font-semibold text-ink-950">Order Food</Link></div></div></div>;
  return <div className="container-narrow py-8 lg:py-12"><Link to="/" className="mb-6 inline-flex items-center gap-2 text-sm text-ink-400 hover:text-cream-100"><ArrowLeft className="h-4 w-4"/>Back to home</Link><div className="mx-auto max-w-2xl"><span className="text-xs font-semibold uppercase tracking-[0.2em] text-ember-500">Dine In</span><h1 className="mt-2 font-display text-display-lg font-bold text-cream-50">Book a Table</h1><p className="mt-2 text-sm text-ink-300">Choose your preferred time and we'll confirm your table.</p><form onSubmit={submit} className="mt-8 space-y-6"><div className="rounded-2xl border border-ink-700/50 bg-ink-900 p-6"><div className="grid grid-cols-1 gap-4 sm:grid-cols-2"><Input label="Full Name *" value={form.customerName} onChange={e=>update('customerName',e.target.value)} placeholder="Your name"/><Input label="Phone Number *" value={form.customerPhone} onChange={e=>update('customerPhone',e.target.value)} placeholder="+91 98765 43210"/><Input label="Email" type="email" value={form.customerEmail} onChange={e=>update('customerEmail',e.target.value)} placeholder="you@example.com"/><div><label className="mb-2 block text-sm font-medium text-cream-200">Guests *</label><div className="relative"><Users className="pointer-events-none absolute left-3 top-3 h-4 w-4 text-ink-400"/><select value={form.guests} onChange={e=>update('guests',e.target.value)} className="w-full rounded-xl border border-ink-600 bg-ink-950 py-2.5 pl-10 pr-3 text-sm text-cream-100 outline-none focus:border-ember-500">{Array.from({length:20},(_,i)=><option key={i+1} value={i+1}>{i+1} {i===0?'guest':'guests'}</option>)}</select></div></div><div><label className="mb-2 block text-sm font-medium text-cream-200">Date *</label><div className="relative"><CalendarDays className="pointer-events-none absolute left-3 top-3 h-4 w-4 text-ink-400"/><input type="date" min={today} value={form.date} onChange={e=>update('date',e.target.value)} className="w-full rounded-xl border border-ink-600 bg-ink-950 py-2.5 pl-10 pr-3 text-sm text-cream-100 outline-none focus:border-ember-500"/></div></div><div><label className="mb-2 block text-sm font-medium text-cream-200">Time *</label><div className="relative"><Clock3 className="pointer-events-none absolute left-3 top-3 h-4 w-4 text-ink-400"/><input type="time" value={form.time} onChange={e=>update('time',e.target.value)} className="w-full rounded-xl border border-ink-600 bg-ink-950 py-2.5 pl-10 pr-3 text-sm text-cream-100 outline-none focus:border-ember-500"/></div></div></div><Textarea label="Special Request (optional)" value={form.notes} onChange={e=>update('notes',e.target.value)} placeholder="Birthday, window seat, high chair, etc." rows={3}/></div><Button type="submit" fullWidth size="lg" loading={loading}>Request Table <CalendarDays className="h-4 w-4"/></Button></form></div></div>;
}
