import { Router } from 'express';
import crypto from 'node:crypto';
import mongoose from 'mongoose';
import { Order } from '../models/Order';
import { Payment } from '../models/Payment';
import { MenuItem } from '../models/MenuItem';
import { Coupon } from '../models/Coupon';
import { RestaurantSettings } from '../models/RestaurantSettings';
import { authMiddleware, AuthRequest } from '../middleware/auth';
import { error, success, generateOrderNumber } from '../utils/helpers';

const router = Router();
function getRazorpayCredentials(){const keyId=process.env.RAZORPAY_KEY_ID;const keySecret=process.env.RAZORPAY_KEY_SECRET;if(!keyId||!keySecret)throw new Error('Razorpay is not configured. Set RAZORPAY_KEY_ID and RAZORPAY_KEY_SECRET in the backend environment.');return{keyId,keySecret};}
async function razorpayRequest(path:string,method:string,body?:unknown){const{keyId,keySecret}=getRazorpayCredentials();const auth=Buffer.from(`${keyId}:${keySecret}`).toString('base64');const response=await fetch(`https://api.razorpay.com/v1${path}`,{method,headers:{Authorization:`Basic ${auth}`,'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data?.error?.description||`Razorpay request failed (${response.status})`);return data;}

async function buildCheckoutData(req:AuthRequest){const{items,customerName,customerPhone,customerEmail,deliveryAddress,deliveryLatitude,deliveryLongitude,orderNotes,couponCode}=req.body;if(!items?.length)throw new Error('No items in order');if(!customerName||!customerPhone||!deliveryAddress)throw new Error('Name, phone, and address are required');const settings=await RestaurantSettings.findOne();if(!settings)throw new Error('Restaurant settings not configured');if(!settings.isOpen)throw new Error("We're closed right now. Please check back soon.");const orderItems:any[]=[];let subtotal=0;for(const cartItem of items){const menuItem=await MenuItem.findById(cartItem.menuItemId||cartItem.menuItem?.id);if(!menuItem)throw new Error(`Item not found: ${cartItem.name||cartItem.menuItem?.name}`);if(!menuItem.isAvailable)throw new Error(`${menuItem.name} is not available`);const qty=Math.max(1,parseInt(cartItem.quantity)||1);orderItems.push({menuItemId:menuItem._id.toString(),name:menuItem.name,price:Number(menuItem.price),quantity:qty,imageUrl:menuItem.imageUrl||''});subtotal+=menuItem.price*qty;}const tax=subtotal*(settings.taxRate||5)/100;const deliveryFee=settings.deliveryCharge||40;let discount=0;const normalizedCoupon=couponCode?String(couponCode).toUpperCase():'';if(normalizedCoupon){const coupon=await Coupon.findOne({code:normalizedCoupon});if(!coupon)throw new Error('Invalid coupon code');if(!coupon.isActive)throw new Error('Coupon is not active');if(coupon.expiresAt&&new Date(coupon.expiresAt)<new Date())throw new Error('Coupon has expired');if(subtotal<coupon.minOrder)throw new Error(`Minimum order ₹${coupon.minOrder} required for this coupon`);if(coupon.usageLimit&&coupon.usedCount>=coupon.usageLimit)throw new Error('Coupon usage limit reached');if(coupon.discountType==='percentage'){discount=subtotal*coupon.discountValue/100;if(coupon.maxDiscount)discount=Math.min(discount,coupon.maxDiscount);}else discount=coupon.discountValue;}const total=Math.max(0,subtotal+tax+deliveryFee-discount);return{customerName,customerPhone,customerEmail:customerEmail||'',deliveryAddress,deliveryLatitude:deliveryLatitude==null?null:Number(deliveryLatitude),deliveryLongitude:deliveryLongitude==null?null:Number(deliveryLongitude),orderNotes:orderNotes||'',userId:req.userId||null,items:orderItems,couponCode:normalizedCoupon,subtotal,tax,deliveryFee,discount,total};}

async function createFinalOrder(payment:any){if(payment.orderId)return Order.findById(payment.orderId);if(!payment.checkoutData)throw new Error('Payment checkout data is missing');const session=await mongoose.startSession();try{let createdOrder:any=null;await session.withTransaction(async()=>{const current=await Payment.findById(payment._id).session(session);if(!current)throw new Error('Payment record not found');if(current.orderId){createdOrder=await Order.findById(current.orderId).session(session);return;}if(current.status!=='paid')throw new Error('Payment is not paid');const d:any=current.checkoutData;const orderItems=d.items.map((item:any)=>({menuItemId:new mongoose.Types.ObjectId(item.menuItemId),name:item.name,price:Number(item.price),quantity:item.quantity,imageUrl:item.imageUrl||''}));if(orderItems.some((item:any)=>!Number.isFinite(item.price)||item.price<0))throw new Error('Invalid item price in payment checkout');const order=(await Order.create([{orderNumber:generateOrderNumber(),userId:d.userId||null,customerName:d.customerName,customerPhone:d.customerPhone,customerEmail:d.customerEmail||'',deliveryAddress:d.deliveryAddress,deliveryLatitude:d.deliveryLatitude??null,deliveryLongitude:d.deliveryLongitude??null,orderNotes:d.orderNotes||'',status:'placed',paymentMethod:'razorpay',paymentStatus:'paid',items:orderItems,subtotal:d.subtotal,tax:d.tax,deliveryFee:d.deliveryFee,discount:d.discount,total:d.total,couponCode:d.couponCode||'',estimatedMinutes:45}],{session}))[0];createdOrder=order;if(d.couponCode)await Coupon.findOneAndUpdate({code:d.couponCode},{$inc:{usedCount:1}},{session});await Payment.findByIdAndUpdate(current._id,{orderId:order._id,userId:d.userId||null},{session});});return createdOrder;}finally{await session.endSession();}}

router.post('/razorpay/checkout',authMiddleware,async(req:AuthRequest,res:any)=>{try{const data=await buildCheckoutData(req);const amountPaise=Math.round(Number(data.total)*100);if(!Number.isInteger(amountPaise)||amountPaise<=0)return error(res,'Invalid order amount',400);const razorpayOrder=await razorpayRequest('/orders','POST',{amount:amountPaise,currency:'INR',receipt:`alnihar_${Date.now()}`.slice(0,40),notes:{alNiharCheckout:'true',userId:req.userId||''}});await Payment.create({orderId:null,userId:req.userId||null,razorpayOrderId:razorpayOrder.id,amount:Number(data.total),status:'pending',checkoutData:data});return success(res,{razorpayOrderId:razorpayOrder.id,amount:amountPaise,currency:'INR',keyId:getRazorpayCredentials().keyId,orderNumber:razorpayOrder.receipt});}catch(e:any){return error(res,e.message||'Failed to create Razorpay checkout',400);}});

router.post('/razorpay/verify',authMiddleware,async(req:AuthRequest,res:any)=>{try{const{razorpayOrderId,razorpayPaymentId,razorpaySignature}=req.body;if(!razorpayOrderId||!razorpayPaymentId||!razorpaySignature)return error(res,'Incomplete Razorpay payment response',400);const payment=await Payment.findOne({razorpayOrderId});if(!payment)return error(res,'Payment session not found',404);if(payment.userId&&payment.userId.toString()!==req.userId)return error(res,'You cannot verify this payment',403);if(payment.status==='paid'&&payment.orderId)return success(res,await Order.findById(payment.orderId),'Payment already verified');const{keySecret}=getRazorpayCredentials();const expectedSignature=crypto.createHmac('sha256',keySecret).update(`${razorpayOrderId}|${razorpayPaymentId}`).digest('hex');const valid=expectedSignature.length===razorpaySignature.length&&crypto.timingSafeEqual(Buffer.from(expectedSignature),Buffer.from(razorpaySignature));if(!valid){await Payment.findByIdAndUpdate(payment._id,{razorpayPaymentId,razorpaySignature,status:'failed'});return error(res,'Payment signature verification failed',400);}await Payment.findByIdAndUpdate(payment._id,{razorpayPaymentId,razorpaySignature,status:'paid'});const paid=await Payment.findById(payment._id);const order=await createFinalOrder(paid);return success(res,order,'Payment verified and order created');}catch(e:any){return error(res,e.message||'Failed to verify Razorpay payment',500);}});

export async function handleRazorpayWebhook(req:any,res:any){try{const webhookSecret=process.env.RAZORPAY_WEBHOOK_SECRET;if(!webhookSecret)return res.status(500).json({success:false,message:'Razorpay webhook secret is not configured'});const signature=req.headers['x-razorpay-signature'];if(typeof signature!=='string'||!Buffer.isBuffer(req.body))return res.status(400).json({success:false,message:'Invalid webhook request'});const expected=crypto.createHmac('sha256',webhookSecret).update(req.body).digest('hex');if(expected.length!==signature.length||!crypto.timingSafeEqual(Buffer.from(expected),Buffer.from(signature)))return res.status(400).json({success:false,message:'Invalid webhook signature'});const event=JSON.parse(req.body.toString('utf8'));const paymentEntity=event?.payload?.payment?.entity;const razorpayOrderId=paymentEntity?.order_id;const razorpayPaymentId=paymentEntity?.id;if(!razorpayOrderId)return res.json({success:true});const payment=await Payment.findOne({razorpayOrderId});if(!payment)return res.json({success:true});if(event.event==='payment.captured'||event.event==='order.paid'){await Payment.findByIdAndUpdate(payment._id,{status:'paid',razorpayPaymentId:razorpayPaymentId||payment.razorpayPaymentId});const paid=await Payment.findById(payment._id);if(paid)await createFinalOrder(paid);}else if(event.event==='payment.failed'&&payment.status!=='paid'){await Payment.findByIdAndUpdate(payment._id,{status:'failed',razorpayPaymentId:razorpayPaymentId||payment.razorpayPaymentId});}return res.json({success:true});}catch(e){console.error('Razorpay webhook error:',e);return res.status(500).json({success:false});}}
export default router;
